package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/shirou/swagger_sample/client/user"
)

// Default swaggertest HTTP client.
var Default = NewHTTPClient(nil)

// NewHTTPClient creates a new swaggertest HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Swaggertest {
	if formats == nil {
		formats = strfmt.Default
	}
	transport := httptransport.New("localhost:8000", "/", []string{"http"})
	return New(transport, formats)
}

// New creates a new swaggertest client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Swaggertest {
	cli := new(Swaggertest)
	cli.Transport = transport

	cli.User = user.New(transport, formats)

	return cli
}

// Swaggertest is a client for swaggertest
type Swaggertest struct {
	User *user.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Swaggertest) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.User.SetTransport(transport)

}
